version: 2
updates:
  - package-ecosystem: gomod
    directory: /server
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /sdk/js
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
